/**
 * commands.ts
 * Implements the three RPGLE AI Assistant commands.
 * Each command:
 *   1. Gets the selected code (or full file as fallback)
 *   2. Shows a loading indicator
 *   3. Calls the AI service
 *   4. Renders the result in a new Markdown editor tab
 */

import * as vscode from 'vscode';
import { explainCode, generateDocs, analyzeFullFile, AIResponse } from './aiService';

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Returns the currently selected text in the active editor.
 * Returns null if nothing is selected.
 */
function getSelectedText(editor: vscode.TextEditor): string | null {
  const selection = editor.selection;
  if (selection.isEmpty) {
    return null;
  }
  return editor.document.getText(selection);
}

/**
 * Returns the full content of the active editor's document.
 */
function getFullFileText(editor: vscode.TextEditor): string {
  return editor.document.getText();
}

/**
 * Opens a new untitled Markdown document tab and writes content to it.
 * @param title  - Used as a comment header at the top of the document
 * @param content - Markdown content to display
 */
async function showMarkdownResult(title: string, content: string): Promise<void> {
  // Build a nice header with timestamp
  const now = new Date().toLocaleString();
  const fullContent = `<!-- ${title} — Generated by RPGLE AI Assistant on ${now} -->\n\n${content}`;

  // Create a new untitled document with Markdown language mode
  const doc = await vscode.workspace.openTextDocument({
    language: 'markdown',
    content: fullContent
  });

  // Open it in a side-by-side column if possible, otherwise just open it
  await vscode.window.showTextDocument(doc, {
    viewColumn: vscode.ViewColumn.Beside,
    preview: false // Keep the tab open (not preview mode)
  });
}

/**
 * Shows a footer with token usage stats appended to the AI response.
 */
function appendMetadata(response: AIResponse, sourceInfo: string): string {
  return (
    response.content +
    `\n\n---\n` +
    `*🤖 Generated by RPGLE AI Assistant | ` +
    `Model: \`${response.model}\` | ` +
    `Tokens used: ${response.tokensUsed} | ` +
    `Source: ${sourceInfo}*`
  );
}

/**
 * Generic wrapper that:
 * - validates the editor state
 * - gets code (selection or full file)
 * - runs the AI call inside a progress indicator
 * - shows the result or surfaces errors
 */
async function runAICommand(options: {
  commandName: string;
  requireSelection: boolean;
  fallbackToFullFile: boolean;
  sourceLabel: string;
  aiFunction: (code: string) => Promise<AIResponse>;
  outputTitle: string;
}): Promise<void> {
  const { commandName, requireSelection, fallbackToFullFile, sourceLabel, aiFunction, outputTitle } = options;

  // 1. Validate an editor is open
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showErrorMessage(
      '⚠️ RPGLE AI: No active editor found. Please open an RPGLE file first.'
    );
    return;
  }

  // 2. Get the code to analyze
  let code = getSelectedText(editor);
  let actualSourceLabel = `selected code`;

  if (!code) {
    if (requireSelection) {
      vscode.window.showWarningMessage(
        `⚠️ RPGLE AI: Please select some RPGLE code first, then run "${commandName}".`
      );
      return;
    }

    if (fallbackToFullFile) {
      code = getFullFileText(editor);
      actualSourceLabel = `full file (${editor.document.fileName.split('/').pop() ?? 'untitled'})`;

      if (!code || code.trim() === '') {
        vscode.window.showWarningMessage('⚠️ RPGLE AI: The current file is empty.');
        return;
      }
    }
  }

  if (!code || code.trim() === '') {
    vscode.window.showWarningMessage('⚠️ RPGLE AI: The selected code is empty.');
    return;
  }

  // 3. Run the AI call with a progress indicator in the status bar
  await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `🔄 RPGLE AI: ${outputTitle}...`,
      cancellable: false
    },
    async (progress) => {
      progress.report({ message: 'Sending code to AI...' });

      try {
        const response = await aiFunction(code!);
        progress.report({ message: 'Rendering result...' });

        const finalContent = appendMetadata(response, actualSourceLabel);
        await showMarkdownResult(outputTitle, finalContent);

        vscode.window.showInformationMessage(
          `✅ RPGLE AI: ${outputTitle} complete! (${response.tokensUsed} tokens used)`
        );

      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        vscode.window.showErrorMessage(`❌ RPGLE AI Error: ${message}`, 'Open Settings').then(
          (choice) => {
            if (choice === 'Open Settings') {
              vscode.commands.executeCommand('workbench.action.openSettings', 'rpgleAI');
            }
          }
        );
      }
    }
  );
}

// ─── Command Implementations ──────────────────────────────────────────────────

/**
 * "Explain RPG Code" command.
 * Requires a text selection. Sends selected RPGLE code to AI for a plain-English explanation.
 */
export async function explainCodeCommand(): Promise<void> {
  await runAICommand({
    commandName: 'Explain RPG Code',
    requireSelection: false, // We'll show a warning but not hard-block
    fallbackToFullFile: true,
    sourceLabel: 'selected code',
    aiFunction: explainCode,
    outputTitle: 'RPGLE Code Explanation'
  });
}

/**
 * "Generate RPG Documentation" command.
 * Works on selected code, or falls back to the full file.
 * Outputs structured Markdown documentation.
 */
export async function generateDocsCommand(): Promise<void> {
  await runAICommand({
    commandName: 'Generate RPG Documentation',
    requireSelection: false,
    fallbackToFullFile: true,
    sourceLabel: 'source code',
    aiFunction: generateDocs,
    outputTitle: 'RPGLE Program Documentation'
  });
}

/**
 * "Analyze Full RPG File" command (bonus feature).
 * Always uses the full file, never just a selection.
 * Performs a deep code quality and logic analysis.
 */
export async function analyzeFullFileCommand(): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showErrorMessage(
      '⚠️ RPGLE AI: No active editor found. Please open an RPGLE file first.'
    );
    return;
  }

  const code = getFullFileText(editor);
  const fileName = editor.document.fileName.split('/').pop() ?? 'untitled';

  if (!code || code.trim() === '') {
    vscode.window.showWarningMessage('⚠️ RPGLE AI: The current file is empty.');
    return;
  }

  await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `🔍 RPGLE AI: Analyzing ${fileName}...`,
      cancellable: false
    },
    async (progress) => {
      progress.report({ message: 'Running full file analysis...' });

      try {
        const response = await analyzeFullFile(code);
        progress.report({ message: 'Rendering analysis...' });

        const finalContent = appendMetadata(response, `full file: ${fileName}`);
        await showMarkdownResult('RPGLE Full File Analysis', finalContent);

        vscode.window.showInformationMessage(
          `✅ RPGLE AI: Analysis of "${fileName}" complete! (${response.tokensUsed} tokens used)`
        );

      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        vscode.window.showErrorMessage(`❌ RPGLE AI Error: ${message}`, 'Open Settings').then(
          (choice) => {
            if (choice === 'Open Settings') {
              vscode.commands.executeCommand('workbench.action.openSettings', 'rpgleAI');
            }
          }
        );
      }
    }
  );
}
